import type { Formation } from "./types";

export const offensiveFormations: Formation[] = [
  {
    id: "spread",
    label: "Spread 2x2",
    teamSize: 11,
    description: "Formación abierta con cuatro receptores y un corredor.",
    players: [
      { id: "qb", label: "QB", role: "Quarterback", position: { x: 400, y: 360 } },
      { id: "rb", label: "RB", role: "Running Back", position: { x: 440, y: 410 } },
      { id: "wr1", label: "X", role: "Wide Receiver", position: { x: 200, y: 260 } },
      { id: "wr2", label: "Z", role: "Wide Receiver", position: { x: 600, y: 260 } },
      { id: "slot1", label: "H", role: "Slot Receiver", position: { x: 320, y: 280 } },
      { id: "slot2", label: "Y", role: "Slot Receiver", position: { x: 480, y: 280 } },
      { id: "lt", label: "LT", role: "Left Tackle", position: { x: 320, y: 340 } },
      { id: "lg", label: "LG", role: "Left Guard", position: { x: 340, y: 340 } },
      { id: "c", label: "C", role: "Center", position: { x: 360, y: 340 } },
      { id: "rg", label: "RG", role: "Right Guard", position: { x: 380, y: 340 } },
      { id: "rt", label: "RT", role: "Right Tackle", position: { x: 400, y: 340 } },
    ],
  },
  {
    id: "trips",
    label: "Trips Right",
    teamSize: 11,
    description: "Tres receptores al lado derecho para crear superioridad numérica.",
    players: [
      { id: "qb", label: "QB", role: "Quarterback", position: { x: 420, y: 360 } },
      { id: "rb", label: "RB", role: "Running Back", position: { x: 460, y: 410 } },
      { id: "wr1", label: "X", role: "Wide Receiver", position: { x: 220, y: 260 } },
      { id: "wr2", label: "Z", role: "Wide Receiver", position: { x: 620, y: 240 } },
      { id: "slot1", label: "H", role: "Slot Receiver", position: { x: 520, y: 260 } },
      { id: "slot2", label: "Y", role: "Slot Receiver", position: { x: 520, y: 300 } },
      { id: "lt", label: "LT", role: "Left Tackle", position: { x: 340, y: 340 } },
      { id: "lg", label: "LG", role: "Left Guard", position: { x: 360, y: 340 } },
      { id: "c", label: "C", role: "Center", position: { x: 380, y: 340 } },
      { id: "rg", label: "RG", role: "Right Guard", position: { x: 400, y: 340 } },
      { id: "rt", label: "RT", role: "Right Tackle", position: { x: 420, y: 340 } },
    ],
  },
  {
    id: "flag-2x2",
    label: "Flag 2x2 (5v5)",
    teamSize: 5,
    description: "Formación balanceada para Flag Football 5 vs 5.",
    players: [
      { id: "qb", label: "QB", role: "Quarterback", position: { x: 400, y: 360 } },
      { id: "wr1", label: "X", role: "Wide Receiver", position: { x: 240, y: 260 } },
      { id: "wr2", label: "Z", role: "Wide Receiver", position: { x: 560, y: 260 } },
      { id: "slot1", label: "H", role: "Slot Receiver", position: { x: 320, y: 300 } },
      { id: "slot2", label: "Y", role: "Slot Receiver", position: { x: 480, y: 300 } },
    ],
  },
];

export const defensiveFormations: Formation[] = [
  {
    id: "4-3",
    label: "4-3 Base",
    teamSize: 11,
    description: "Cuatro linieros defensivos y tres linebackers.",
    players: [
      { id: "le", label: "LE", role: "Defensive End", position: { x: 320, y: 300 } },
      { id: "dt1", label: "DT", role: "Defensive Tackle", position: { x: 360, y: 300 } },
      { id: "dt2", label: "DT", role: "Defensive Tackle", position: { x: 400, y: 300 } },
      { id: "re", label: "RE", role: "Defensive End", position: { x: 440, y: 300 } },
      { id: "sam", label: "SAM", role: "Linebacker", position: { x: 320, y: 250 } },
      { id: "mike", label: "MIKE", role: "Linebacker", position: { x: 380, y: 250 } },
      { id: "will", label: "WILL", role: "Linebacker", position: { x: 440, y: 250 } },
      { id: "cb1", label: "CB", role: "Cornerback", position: { x: 260, y: 200 } },
      { id: "cb2", label: "CB", role: "Cornerback", position: { x: 520, y: 200 } },
      { id: "fs", label: "FS", role: "Safety", position: { x: 360, y: 150 } },
      { id: "ss", label: "SS", role: "Safety", position: { x: 420, y: 150 } },
    ],
  },
  {
    id: "3-4",
    label: "3-4 Pressure",
    teamSize: 11,
    description: "Tres linieros y cuatro linebackers para presionar o cubrir.",
    players: [
      { id: "de1", label: "DE", role: "Defensive End", position: { x: 340, y: 300 } },
      { id: "nt", label: "NT", role: "Nose Tackle", position: { x: 380, y: 300 } },
      { id: "de2", label: "DE", role: "Defensive End", position: { x: 420, y: 300 } },
      { id: "olb1", label: "OLB", role: "Outside LB", position: { x: 300, y: 260 } },
      { id: "ilb1", label: "ILB", role: "Inside LB", position: { x: 360, y: 250 } },
      { id: "ilb2", label: "ILB", role: "Inside LB", position: { x: 400, y: 250 } },
      { id: "olb2", label: "OLB", role: "Outside LB", position: { x: 460, y: 260 } },
      { id: "cb1", label: "CB", role: "Cornerback", position: { x: 260, y: 200 } },
      { id: "cb2", label: "CB", role: "Cornerback", position: { x: 520, y: 200 } },
      { id: "fs", label: "FS", role: "Free Safety", position: { x: 340, y: 150 } },
      { id: "ss", label: "SS", role: "Strong Safety", position: { x: 440, y: 150 } },
    ],
  },
  {
    id: "flag-2-3",
    label: "Flag 2-3 Zone (5v5)",
    teamSize: 5,
    description: "Defensa base para Flag Football 5 vs 5 con dos rushers y tres defensivos.",
    players: [
      { id: "r1", label: "R1", role: "Rusher", position: { x: 360, y: 320 } },
      { id: "r2", label: "R2", role: "Rusher", position: { x: 440, y: 320 } },
      { id: "lb", label: "LB", role: "Linebacker", position: { x: 400, y: 260 } },
      { id: "cb1", label: "CB", role: "Cornerback", position: { x: 320, y: 220 } },
      { id: "cb2", label: "CB", role: "Cornerback", position: { x: 480, y: 220 } },
    ],
  },
];
